#hyperparameters
ALPHA: 0.01
GAMMA: 0.99
BATCH_SIZE: 128
EPSILON: 1.0
EPSILON_DECAY: 0.994
MEMORY_SIZE: 10000
EPISODES : 1000
MAX_STEP : 500
TAU : 5
SEED : 0

#Algorithm
ALGORITHM : "DQN"

#network information
HIDDEN_LAYERS:
  - 128
  - 128
state_size : 4
action_size : 2

#hardware
DEVICE : cpu

#Environment
ENVIRONMENT : "CartPole-v1"
RENDER_MODE : "human"

#RL Signals
ACTIONS : [0, 1]