# Agent
algorithm : "DQN"
EPISODES : 500

# Environment
environment : "CartPole-v1"
RENDER_MODE : "human"

# Run
DEVICE : cuda
SEED : 0
mode : "train"

#Hyperparameters
ALPHA : 0.001
GAMMA : 0.99
EPSILON : 1.0
EPSILON_DECAY : 0.994

#Save
PATH : "algorithms/neural_networks/models"