#hyperparameters
ALPHA: 0.001
GAMMA: 0.98
BATCH_SIZE: 128
EPSILON: 1.0
EPSILON_DECAY: 0.995
MEMORY_SIZE: 10000
EPISODES : 1000
MAX_STEP : 500
TAU : 10
SEED : 0

#Algorithm
ALGORITHM : "DQN"

#network information
HIDDEN_LAYERS:
  - 64
  - 16
state_size : 4
action_size : 2

#hardware
DEVICE : cpu

#Environment
ENVIRONMENT : "CartPole-v1"
RENDER_MODE : "human"

#RL Signals
ACTIONS : [0, 1]