# Agent
algorithm : "DQN"
EPISODES : 1000

# Environment
environment : "CartPole-v1"
RENDER_MODE : None

# Run
DEVICE : cuda
SEED : 0
mode : "train"

#Hyperparameters
ALPHA : 0.001
GAMMA : 0.99
EPSILON : 1.0
EPSILON_DECAY : 0.997
EPSILON_THRESHOLD: 0.2

#Save
PATH : "algorithms/neural_networks/models"
PATH_TEST : "algorithms/neural_networks/models/CartPole-v11709036509.6563454.pth"
