# Agent
algorithm : "DQN"
EPISODES : 2000

# Environment
environment : "LunarLander-v2"
RENDER_MODE : None

# Run
DEVICE : cuda
SEED : 0
mode : "train"

#Hyperparameters
ALPHA : 0.001
GAMMA : 0.99
EPSILON : 1.0
EPSILON_DECAY : 0.9965
EPSILON_THRESHOLD: 0.1

#Save
PATH : "algorithms/neural_networks/models"